version: '3'
services:
  nginx:
    image: nginx:1.11.3
    ports:
    - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: 172.21.0.2:24224
        tag: docker.{{.FullID}}
    depends_on:
    - fluentd
  fluentd:
    image: fluent/fluentd:v0.14.14-debian
    ports:
    - "24224:24224"
    - "24224:24224/udp"
    volumes:
    - ./data:/fluentd/log
